// Additional high-frequency/useful learning cards.
// Appended only, so existing numeric SRS card indices keep their meaning and saved progress is preserved.
const extraCore = [
  ['为','wèi / wéi','for; because of / to do; become','因为','yīnwèi · because'],
  ['子','zǐ','child; son; noun element','孩子','háizi · child'],
  ['地','dì / de','earth; place / adverb marker','地方','dìfang · place'],
  ['出','chū','go out; come out','出去','chūqù · go out'],
  ['之','zhī','of; it (formal)','之前','zhīqián · before'],
  ['过','guò','pass; cross; experiential particle','去过','qùguo · have been to'],
  ['她','tā','she; her','她很好','tā hěn hǎo · she is well'],
  ['么','me','suffix in question words','什么','shénme · what'],
  ['心','xīn','heart; mind','小心','xiǎoxīn · be careful'],
  ['日','rì','day; sun','生日','shēngrì · birthday'],
  ['于','yú','at; in; to (formal)','关于','guānyú · about; regarding'],
  ['起','qǐ','rise; start','起床','qǐchuáng · get up'],
  ['发','fā','send; issue; develop','发现','fāxiàn · discover'],
  ['成','chéng','become; succeed','成功','chénggōng · succeed'],
  ['只','zhǐ','only','只有','zhǐyǒu · only have; only if'],
  ['作','zuò','do; make; work','工作','gōngzuò · work'],
  ['当','dāng','be; act as; when','当然','dāngrán · of course'],
  ['把','bǎ','hold; object-marking particle','把门打开','bǎ mén dǎkāi · open the door'],
  ['法','fǎ','method; law','办法','bànfǎ · solution; way'],
  ['此','cǐ','this (formal)','因此','yīncǐ · therefore'],
  ['实','shí','real; true','其实','qíshí · actually'],
  ['回','huí','return; time/occasion','回来','huílái · come back'],
  ['二','èr','two','二十','èrshí · twenty'],
  ['理','lǐ','reason; manage','理解','lǐjiě · understand'],
  ['部','bù','part; department; classifier','一部手机','yí bù shǒujī · a mobile phone'],
  ['话','huà','speech; words','说话','shuōhuà · speak; talk'],
  ['等','děng','wait; and so on','等一下','děng yíxià · wait a moment'],
  ['制','zhì','system; make; control','制度','zhìdù · system'],
  ['最','zuì','most; -est','最好','zuì hǎo · best'],
  ['间','jiān','room; between; classifier','房间','fángjiān · room'],
  ['业','yè','business; profession; studies','专业','zhuānyè · major; specialty'],
  ['全','quán','whole; all','全部','quánbù · all of it'],
  ['因','yīn','cause; because','因为','yīnwèi · because'],
  ['期','qī','period; term','星期','xīngqī · week'],
  ['月','yuè','month; moon','这个月','zhège yuè · this month'],
  ['别','bié','do not; other','别担心','bié dānxīn · don’t worry'],
  ['车','chē','vehicle; car','火车','huǒchē · train'],
  ['被','bèi','by; passive marker','被子','bèizi · quilt'],
  ['给','gěi','give; for; to','给你','gěi nǐ · give it to you'],
  ['正','zhèng','right; exactly; currently','正在','zhèngzài · currently doing'],
  ['情','qíng','feeling; situation','事情','shìqing · matter; thing'],
  ['者','zhě','person who; -er','记者','jìzhě · journalist'],
  ['或','huò','or; perhaps','或者','huòzhě · or'],
  ['向','xiàng','toward; direction','方向','fāngxiàng · direction'],
  ['位','wèi','position; polite classifier for people','一位老师','yí wèi lǎoshī · a teacher'],
  ['由','yóu','from; by; due to','自由','zìyóu · freedom'],
  ['先','xiān','first; before','先吃饭','xiān chīfàn · eat first'],
  ['什','shén','what (in 什么)','什么','shénme · what'],
  ['它','tā','it','它很好','tā hěn hǎo · it is good'],
  ['并','bìng','and; moreover; emphatic with negatives','并不','bìng bù · actually not'],
  ['表','biǎo','table; form; show','表示','biǎoshì · express; indicate'],
  ['走','zǒu','walk; leave','走吧','zǒu ba · let’s go'],
  ['使','shǐ','make; cause; use','使用','shǐyòng · use'],
  ['第','dì','ordinal prefix','第一','dì-yī · first'],
  ['让','ràng','let; allow; make','让我看看','ràng wǒ kànkan · let me see'],
  ['名','míng','name; classifier for people','名字','míngzi · name'],
  ['其','qí','its; their; that (formal)','其他','qítā · other'],
  ['内','nèi','inside; within','里面','lǐmiàn · inside'],
  ['接','jiē','receive; pick up; connect','接电话','jiē diànhuà · answer the phone'],
  ['平','píng','level; peaceful','平时','píngshí · usually'],
  ['许','xǔ','allow; perhaps','也许','yěxǔ · perhaps'],
  ['做','zuò','do; make','做什么？','zuò shénme? · do what?'],
  ['原','yuán','original; source','原来','yuánlái · originally; so that’s why'],
  ['城','chéng','city; town','城市','chéngshì · city'],
  ['儿','ér','child; -r sound suffix','女儿','nǚ’ér · daughter'],
  ['每','měi','every; each','每天','měitiān · every day'],
  ['比','bǐ','compare; than','比较','bǐjiào · relatively; compare'],
  ['真','zhēn','true; really','真的','zhēn de · really; true'],
  ['常','cháng','often; usual','经常','jīngcháng · often'],
  ['色','sè','color','颜色','yánsè · color'],
  ['声','shēng','sound; voice','声音','shēngyīn · sound; voice'],
  ['相','xiāng','each other; mutually','相信','xiāngxìn · believe'],
  ['风','fēng','wind; style','刮风','guā fēng · be windy'],
  ['张','zhāng','open; classifier for flat objects','一张票','yì zhāng piào · one ticket'],
  ['通','tōng','through; connect; understand','交通','jiāotōng · transportation'],
  ['放','fàng','put; release','放这里','fàng zhèlǐ · put it here'],
  ['件','jiàn','item; classifier for matters/clothes','一件衣服','yí jiàn yīfu · one item of clothing'],
  ['光','guāng','light; only; bare','阳光','yángguāng · sunlight'],
  ['门','mén','door; gate','开门','kāi mén · open the door'],
  ['气','qì','air; gas; mood','天气','tiānqì · weather'],
  ['非','fēi','not; non-; must','非常','fēicháng · very; extremely'],
  ['完','wán','finish; complete','吃完了','chī wán le · finished eating'],
  ['空','kōng','empty; free','有空吗？','yǒu kòng ma? · are you free?'],
  ['吃','chī','eat','吃饭','chīfàn · eat; have a meal'],
  ['请','qǐng','please; invite','请问','qǐngwèn · excuse me; may I ask'],
  ['住','zhù','live; stay','住哪里？','zhù nǎlǐ? · where do you live/stay?'],
  ['钱','qián','money','多少钱？','duōshao qián? · how much?'],
  ['早','zǎo','early; morning','早上好','zǎoshang hǎo · good morning'],
  ['玩','wán','play; have fun','出去玩','chūqù wán · go out for fun'],
  ['再','zài','again; then','再见','zàijiàn · goodbye'],
  ['才','cái','only then; only','我才知道','wǒ cái zhīdào · I only just found out'],
  ['呢','ne','question/topic particle','你呢？','nǐ ne? · and you?'],
  ['快','kuài','fast; soon','快一点','kuài yìdiǎn · a bit faster'],
  ['谁','shéi','who','他是谁？','tā shì shéi? · who is he?'],
  ['站','zhàn','stand; station','火车站','huǒchēzhàn · train station'],
  ['找','zhǎo','look for; find; give change','找不到','zhǎo bú dào · can’t find it'],
  ['衣','yī','clothing','衣服','yīfu · clothes'],
  ['往','wǎng','toward','往前走','wǎng qián zǒu · go straight ahead'],
  ['离','lí','be away from; leave','离这里很近','lí zhèlǐ hěn jìn · it’s close to here'],
  ['岁','suì','years old','二十岁','èrshí suì · twenty years old'],
  ['笑','xiào','smile; laugh','笑一笑','xiào yí xiào · give a smile'],
  ['新','xīn','new','新朋友','xīn péngyou · new friend'],
  ['场','chǎng','place; event; classifier','机场','jīchǎng · airport'],
  ['师','shī','teacher; master','老师','lǎoshī · teacher'],
  ['员','yuán','member; employee','服务员','fúwùyuán · server; attendant'],
  ['认','rèn','recognize; admit','认识','rènshi · know; meet'],
  ['亲','qīn','close; relative','亲人','qīnrén · family member'],
  ['病','bìng','illness; sick','生病','shēngbìng · get sick'],
  ['元','yuán','yuan; unit','十元','shí yuán · ten yuan'],
  ['跟','gēn','with; follow','跟我来','gēn wǒ lái · come with me'],
  ['更','gèng','even more','更好','gèng hǎo · better'],
  ['卖','mài','sell','卖完了','mài wán le · sold out'],
  ['您','nín','you (polite)','您好','nín hǎo · hello (polite)']
];

const existingCoreCharacters = new Set(core.map(item => item[0]));
core.push(...extraCore.filter(item => !existingCoreCharacters.has(item[0])));
