#!/usr/bin/env python3
"""Build the app's Core 1000 metadata from open frequency + HSK data.

Sources:
- HanziDB.csv (Jun Da frequency ordering): MIT-licensed repository data.
- complete-hsk-vocabulary: MIT-licensed structured HSK vocabulary data.

The generated JavaScript keeps hand-curated cards when they already exist and
adds missing top-1000 characters with pinyin, a concise definition, and up to
four common HSK words. It never touches learner progress.
"""
from __future__ import annotations

import csv
import io
import json
import re
import urllib.request
from pathlib import Path

HANZI_URL = "https://raw.githubusercontent.com/ruddfawcett/hanziDB.csv/master/hanzi_db.csv"
HSK_URL = "https://raw.githubusercontent.com/drkameleon/complete-hsk-vocabulary/main/complete.json"
OUT = Path(__file__).resolve().parents[1] / "core1000-data.js"
HANZI_RE = re.compile(r"^[\u3400-\u9fff]{2,4}$")


def download(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "mandarin-fast-track-core-builder/1.0"})
    with urllib.request.urlopen(req, timeout=60) as response:
        return response.read().decode("utf-8")


def level_score(levels) -> int:
    values = []
    for level in levels or []:
        m = re.match(r"new-(\d+)", str(level))
        if m:
            values.append(int(m.group(1)))
    return min(values) if values else 99


def clean_meaning(text: str) -> str:
    text = re.sub(r"\s+", " ", str(text or "")).strip()
    return text[:180]


def main() -> None:
    hanzi_rows = list(csv.DictReader(io.StringIO(download(HANZI_URL))))[:1000]
    vocab = json.loads(download(HSK_URL))

    words_by_char: dict[str, list[dict]] = {}
    for item in vocab:
        word = str(item.get("simplified") or "").strip()
        if not HANZI_RE.match(word):
            continue
        forms = item.get("forms") or []
        if not forms:
            continue
        form = forms[0] or {}
        trans = form.get("transcriptions") or {}
        pinyin = str(trans.get("pinyin") or "").strip()
        meanings = form.get("meanings") or []
        meaning = clean_meaning(meanings[0] if meanings else "")
        if not pinyin or not meaning:
            continue
        frequency = item.get("frequency")
        try:
            frequency = int(frequency)
        except (TypeError, ValueError):
            frequency = 10**9
        entry = {
            "zh": word,
            "pinyin": pinyin,
            "meaning": meaning,
            "frequency": frequency,
            "level": level_score(item.get("level")),
        }
        for char in set(word):
            words_by_char.setdefault(char, []).append(entry)

    metadata = []
    for row in hanzi_rows:
        char = row["character"].strip()
        candidates = words_by_char.get(char, [])
        candidates.sort(key=lambda w: (w["level"], w["frequency"], len(w["zh"]), w["zh"]))
        seen = set()
        words = []
        for word in candidates:
            if word["zh"] in seen:
                continue
            seen.add(word["zh"])
            words.append({k: word[k] for k in ("zh", "pinyin", "meaning")})
            if len(words) == 4:
                break
        metadata.append({
            "rank": int(row["frequency_rank"]),
            "char": char,
            "pinyin": row.get("pinyin", "").strip(),
            "meaning": clean_meaning(row.get("definition", "")) or "common Mandarin character",
            "words": words,
        })

    payload = json.dumps(metadata, ensure_ascii=False, separators=(",", ":"))
    js = f"""// AUTO-GENERATED by scripts/build_core1000.py. Do not edit by hand.\n// Frequency ordering: HanziDB / Jun Da. Word examples: complete-hsk-vocabulary.\nconst core1000Meta = {payload};\nconst core1000ByChar = Object.fromEntries(core1000Meta.map(item => [item.char, item]));\nconst coreFrequencyRank = Object.fromEntries(core1000Meta.map(item => [item.char, item.rank]));\nglobalThis.core1000Meta = core1000Meta;\nglobalThis.core1000ByChar = core1000ByChar;\nglobalThis.coreFrequencyRank = coreFrequencyRank;\n\n// Preserve the hand-curated cards already in the app. Add only missing frequency-core cards.\nconst existingCoreChars = new Set(core.map(item => item[0]));\nfor (const item of core1000Meta) {{\n  if (existingCoreChars.has(item.char)) continue;\n  const word = item.words[0];\n  core.push([\n    item.char,\n    item.pinyin,\n    item.meaning,\n    word?.zh || item.char,\n    word ? `${{word.pinyin}} · ${{word.meaning}}` : `${{item.pinyin}} · ${{item.meaning}}`\n  ]);\n  existingCoreChars.add(item.char);\n}}\n"""
    OUT.write_text(js, encoding="utf-8")
    print(f"Wrote {OUT} with {len(metadata)} ranked characters")


if __name__ == "__main__":
    main()
